//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocol.proto
namespace fantasia
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Packet")]
  public partial class Packet : global::ProtoBuf.IExtensible
  {
    public Packet() {}
    
    private fantasia.Ping _ping = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ping", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.Ping ping
    {
      get { return _ping; }
      set { _ping = value; }
    }
    private fantasia.Lobby _lobby = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lobby", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.Lobby lobby
    {
      get { return _lobby; }
      set { _lobby = value; }
    }
    private fantasia.JoinGame _joinGame = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"joinGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.JoinGame joinGame
    {
      get { return _joinGame; }
      set { _joinGame = value; }
    }
    private fantasia.LeaveGame _leaveGame = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"leaveGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.LeaveGame leaveGame
    {
      get { return _leaveGame; }
      set { _leaveGame = value; }
    }
    private fantasia.Room _room = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.Room room
    {
      get { return _room; }
      set { _room = value; }
    }
    private fantasia.PlayerJoined _playerJoined = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerJoined", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.PlayerJoined playerJoined
    {
      get { return _playerJoined; }
      set { _playerJoined = value; }
    }
    private fantasia.PlayerLeaved _playerLeaved = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playerLeaved", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.PlayerLeaved playerLeaved
    {
      get { return _playerLeaved; }
      set { _playerLeaved = value; }
    }
    private fantasia.Chat _chat = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"chat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.Chat chat
    {
      get { return _chat; }
      set { _chat = value; }
    }
    private fantasia.GameStart _gameStart = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gameStart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.GameStart gameStart
    {
      get { return _gameStart; }
      set { _gameStart = value; }
    }
    private fantasia.Update _update = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"update", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.Update update
    {
      get { return _update; }
      set { _update = value; }
    }
    private fantasia.GameEnd _gameEnd = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gameEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.GameEnd gameEnd
    {
      get { return _gameEnd; }
      set { _gameEnd = value; }
    }
    private fantasia.PlayerStering _playerStering = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"playerStering", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.PlayerStering playerStering
    {
      get { return _playerStering; }
      set { _playerStering = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ping")]
  public partial class Ping : global::ProtoBuf.IExtensible
  {
    public Ping() {}
    
    private int _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Lobby")]
  public partial class Lobby : global::ProtoBuf.IExtensible
  {
    public Lobby() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinGame")]
  public partial class JoinGame : global::ProtoBuf.IExtensible
  {
    public JoinGame() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private fantasia.Ship _ship = fantasia.Ship.GALEON;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ship", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fantasia.Ship.GALEON)]
    public fantasia.Ship ship
    {
      get { return _ship; }
      set { _ship = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaveGame")]
  public partial class LeaveGame : global::ProtoBuf.IExtensible
  {
    public LeaveGame() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room")]
  public partial class Room : global::ProtoBuf.IExtensible
  {
    public Room() {}
    
    private readonly global::System.Collections.Generic.List<fantasia.PlayerJoined> _players = new global::System.Collections.Generic.List<fantasia.PlayerJoined>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fantasia.PlayerJoined> players
    {
      get { return _players; }
    }
  
    private int _localId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"localId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int localId
    {
      get { return _localId; }
      set { _localId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerJoined")]
  public partial class PlayerJoined : global::ProtoBuf.IExtensible
  {
    public PlayerJoined() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private fantasia.PlayerTeam _playerTeam = fantasia.PlayerTeam.NONE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerTeam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fantasia.PlayerTeam.NONE)]
    public fantasia.PlayerTeam playerTeam
    {
      get { return _playerTeam; }
      set { _playerTeam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerLeaved")]
  public partial class PlayerLeaved : global::ProtoBuf.IExtensible
  {
    public PlayerLeaved() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Chat")]
  public partial class Chat : global::ProtoBuf.IExtensible
  {
    public Chat() {}
    
    private int _playerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerStering")]
  public partial class PlayerStering : global::ProtoBuf.IExtensible
  {
    public PlayerStering() {}
    
    private float _dirX = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dirX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dirX
    {
      get { return _dirX; }
      set { _dirX = value; }
    }
    private float _dirY = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dirY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dirY
    {
      get { return _dirY; }
      set { _dirY = value; }
    }
    private fantasia.PlayerStering.Shot _shot = fantasia.PlayerStering.Shot.FRONT;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fantasia.PlayerStering.Shot.FRONT)]
    public fantasia.PlayerStering.Shot shot
    {
      get { return _shot; }
      set { _shot = value; }
    }
    private fantasia.PlayerStering.SwitchBalls _switchBalls = fantasia.PlayerStering.SwitchBalls.NORMAL;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"switchBalls", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(fantasia.PlayerStering.SwitchBalls.NORMAL)]
    public fantasia.PlayerStering.SwitchBalls switchBalls
    {
      get { return _switchBalls; }
      set { _switchBalls = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Shot")]
    public enum Shot
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRONT", Value=1)]
      FRONT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIGHT", Value=2)]
      RIGHT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEFT", Value=3)]
      LEFT = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SwitchBalls")]
    public enum SwitchBalls
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORMAL", Value=1)]
      NORMAL = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStart")]
  public partial class GameStart : global::ProtoBuf.IExtensible
  {
    public GameStart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEnd")]
  public partial class GameEnd : global::ProtoBuf.IExtensible
  {
    public GameEnd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Update")]
  public partial class Update : global::ProtoBuf.IExtensible
  {
    public Update() {}
    
    private readonly global::System.Collections.Generic.List<fantasia.Update.Event> _events = new global::System.Collections.Generic.List<fantasia.Update.Event>();
    [global::ProtoBuf.ProtoMember(1, Name=@"events", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fantasia.Update.Event> events
    {
      get { return _events; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Event")]
  public partial class Event : global::ProtoBuf.IExtensible
  {
    public Event() {}
    
    private fantasia.UpdatePlayers _updatePlayers = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"updatePlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.UpdatePlayers updatePlayers
    {
      get { return _updatePlayers; }
      set { _updatePlayers = value; }
    }
    private fantasia.Dead _dead = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fantasia.Dead dead
    {
      get { return _dead; }
      set { _dead = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _dir = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private float _position = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float position
    {
      get { return _position; }
      set { _position = value; }
    }
    private float _course = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"course", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float course
    {
      get { return _course; }
      set { _course = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePlayers")]
  public partial class UpdatePlayers : global::ProtoBuf.IExtensible
  {
    public UpdatePlayers() {}
    
    private readonly global::System.Collections.Generic.List<fantasia.Player> _players = new global::System.Collections.Generic.List<fantasia.Player>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fantasia.Player> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Dead")]
  public partial class Dead : global::ProtoBuf.IExtensible
  {
    public Dead() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Ship")]
    public enum Ship
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GALEON", Value=1)]
      GALEON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CORWETTA", Value=2)]
      CORWETTA = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREGATA", Value=3)]
      FREGATA = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerTeam")]
    public enum PlayerTeam
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=1)]
      NONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RED", Value=2)]
      RED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUE", Value=3)]
      BLUE = 3
    }
  
}